### ISSUE TITLE
gérer exception trop de connexions pg

### ISSUE THREAD

**Issue by abenhamdine** [abenhamdine/cvl-node-extdirect#96]
DEBUG 12:51:36 : countAllAfterFetch() : on est là
DEBUG 12:51:36 : countAllAfterFetch() : on est arrivé à done()
2015-10-21T14:51:36.163+02:00 Fail to end perf measurement of [executeQuery] : tag never started.
DEBUG 12:51:36 : sendResponseFetch() : on est là
2015-10-21T14:51:53.503+02:00 stack: 'error: too many connections for role "uxbrjxzxkbaoxjnqw613"\n at Connection.parseE (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:539:11)\n at Connection.parseMessage (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:366:17)\n at Socket.<anonymous> (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:105:22)\n at Socket.emit (events.js:107:17)\n at readableAddChunk (_stream_readable.js:163:16)\n at Socket.Readable.push (_stream_readable.js:126:10)\n at TCP.onread (net.js:538:20)',
2015-10-21T14:51:53.503+02:00message: 'too many connections for role "uxbrjxzxkbaoxjnqw613"',

**Comment by abenhamdine** [comment]
landed in af30bb1e03308313e75fb6f8292cf4e9271f66a0

**Comment by abenhamdine** [comment]
still present : 

stack: 'error: too many connections for role "uxbrjxzxkbaoxjnqw613"\n at Connection.parseE (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:539:11)\n at Connection.parseMessage (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:366:17)\n at Socket.<anonymous> (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:105:22)\n at Socket.emit (events.js:107:17)\n at readableAddChunk (_stream_readable.js:163:16)\n at Socket.Readable.push (_stream_readable.js:126:10)\n at TCP.onread (net.js:538:20)',
2015-10-26T16:11:59.912+01:00message: 'too many connections for role "uxbrjxzxkbaoxjnqw613"',
2015-10-26T16:11:59.912+01:00{
2015-10-26T16:11:59.913+01:00name: 'error',
2015-10-26T16:11:59.913+01:00length: 115,
2015-10-26T16:11:59.914+01:00code: '53300',
2015-10-26T16:11:59.914+01:00detail: undefined,
2015-10-26T16:11:59.914+01:00severity: 'FATAL',
2015-10-26T16:11:59.915+01:00hint: undefined,
2015-10-26T16:11:59.915+01:00position: undefined,
2015-10-26T16:11:59.915+01:00internalPosition: undefined,
2015-10-26T16:11:59.916+01:00internalQuery: undefined,
2015-10-26T16:11:59.916+01:00where: undefined,
2015-10-26T16:11:59.916+01:00schema: undefined,
2015-10-26T16:11:59.917+01:00dataType: undefined,
2015-10-26T16:11:59.917+01:00table: undefined,
2015-10-26T16:11:59.917+01:00column: undefined,
2015-10-26T16:11:59.918+01:00constraint: undefined,
2015-10-26T16:11:59.918+01:00file: 'miscinit.c',
2015-10-26T16:11:59.918+01:00line: '479',
2015-10-26T16:11:59.919+01:00routine: 'InitializeSessionUserId'
2015-10-26T16:11:59.919+01:00}
2015-10-26T16:11:59.920+01:00ERROR 15:12:00 : Impossible de se connecter à postgres :
2015-10-26T16:11:59.920+01:00true

**Comment by abenhamdine** [comment]
L'erreur est bien renvoyée côté client : response du XHR : 

     [{"type":"rpc","tid":5,"action":"GenericList","method":"read","result":{"message":"Impossible de se connecter à postgres too many connections for role \"uxbrjxzxkbaoxjnqw613\"","auth":true,"success":false}}]

**Comment by abenhamdine** [comment]
et quand on kill toutes les connexions pg depuis la console clevercloud, node crash : 
    
    error: terminating connection due to administrator command
2015-10-26T17:05:28.240+01:00terminating connection due to administrator command
2015-10-26T17:05:28.240+01:00Mon, 26 Oct 2015 16:05:27 GMT : exception non gérée récupérée dans server.js
2015-10-26T17:05:28.241+01:00at Connection.parseMessage (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:366:17)
2015-10-26T17:05:28.241+01:00at Connection.parseE (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:539:11)
2015-10-26T17:05:28.242+01:00at Socket.emit (events.js:107:17)
2015-10-26T17:05:28.242+01:00at Socket.<anonymous> (/home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/node_modules/pg/lib/connection.js:105:22)
2015-10-26T17:05:28.243+01:00at Socket.Readable.push (_stream_readable.js:126:10)
2015-10-26T17:05:28.243+01:00at readableAddChunk (_stream_readable.js:163:16)
2015-10-26T17:05:28.244+01:00at TCP.onread (net.js:538:20)
2015-10-26T17:05:28.245+01:00undefined
2015-10-26T17:05:28.258+01:00npm ERR! argv "node" "/home/bas/.nvm/versions/node/v0.12.7/bin/npm" "start"
2015-10-26T17:05:28.258+01:00npm ERR! Linux 4.1.6+
2015-10-26T17:05:28.259+01:00npm ERR! node v0.12.7
2015-10-26T17:05:28.260+01:00npm ERR! npm v2.14.8
2015-10-26T17:05:28.261+01:00npm ERR! cvl-node-extdirect@0.1.0 start: `node server`
2015-10-26T17:05:28.261+01:00npm ERR! code ELIFECYCLE
2015-10-26T17:05:28.291+01:00npm ERR! Exit status 1
2015-10-26T17:05:28.292+01:00npm ERR!
2015-10-26T17:05:28.325+01:00npm ERR! Failed at the cvl-node-extdirect@0.1.0 start script 'node server'.
2015-10-26T17:05:28.326+01:00npm ERR! This is most likely a problem with the cvl-node-extdirect package,
2015-10-26T17:05:28.327+01:00npm ERR! Tell the author that this fails on your system:
2015-10-26T17:05:28.327+01:00npm ERR! not with npm itself.
2015-10-26T17:05:28.328+01:00npm ERR! node server
2015-10-26T17:05:28.329+01:00npm ERR! npm owner ls cvl-node-extdirect
2015-10-26T17:05:28.329+01:00npm ERR! You can get their info via:
2015-10-26T17:05:28.330+01:00npm ERR! Please include the following file with any support request:
2015-10-26T17:05:28.330+01:00npm ERR! There is likely additional logging output above.
2015-10-26T17:05:28.331+01:00npm ERR! /home/bas/app_38a0ba72-f59d-4ac1-afdf-b5a84e5ca0bc/npm-debug.log
